---
- name: Docker Deploy Playbook
  hosts: MyUbuntu
  tasks:
    #- name: Install Python pip
      #become: yes
      #apt:
         #update_cache: yes
         #name: python3-pip
         #state: latest
    #- name: Install Docker-py python module
      #pip:
         #name: docker
         #state: present
    - name: Run skranking docker image
      docker_container:
         name: skranking
         pull: true
         image: "sk3699/skranking:{{DockerTag}}"
         state: started
         interactive: true
    #- name: Remove old skranking images
      #docker_image:
          #name: sk3699/skranking
          #dangling: true
          #state: absent
    - name: Remove dangling images
      community.docker.docker_prune:
          containers: no
          images: yes
          images_filters:
            dangling: false
