---
- name: Docker Deploy Playbook
  hosts: MyUbuntu
  tasks:
     - name: Run skranking docker image
       docker_container:
         -  name: skranking
            image: "sk3699/skranking:{{DockerTag}}"
            state: started
