---
- name: Docker Deploy Playbook
  hosts: MyUbuntu
  tasks:
    #- name: Install Python pip in Ubuntu
      #become: yes
      #apt:
         #update_cache: yes
         #name: python3-pip
         #state: latest
    #- name: Install Docker-py python module in Ubuntu
      #pip:
         #name: docker
         #state: present
    - name: Run skranking docker image
      docker_container:
         name: skranking
         pull: true
         image: "sk3699/skranking:{{DockerTag}}"
         state: started
         interactive: true
    - name: Remove old skranking images in Ubuntu
      shell: docker rmi -f $(docker images sk3699/skranking)
      ignore_errors: yes
      #shell: |
        #docker rmi -f $(docker images sk3699/skranking)
    #- name: Remove old skranking images
      #docker_prune:
          #images: yes
          #images_filters:
              #dangling: true
              #label: not repository sk3699/skranking
              
    
    #docker image prune -a --filter label!=repository=sk3699/skranking
    #docker rmi -f $(docker images sk3699/skranking)
    
- name: Docker delete sk3699/skranking in Ubuntu-18.04
  hosts: MyUbuntu18_04
  tasks:
    - name: Install Python pip in Ubuntu-18.04
      become: yes
      apt:
         update_cache: yes
         name: python3-pip
         state: latest
    - name: Install Docker-py python module in Ubuntu-18.04
      pip:
         name: docker
         state: present
    - name: Remove skranking images in Ubuntu-18.04
      shell: docker rmi -f $(docker images sk3699/skranking)
      ignore_errors: yes
